services:
  frontend:
    build: ./frontend/frontend  # Assumes you have a Dockerfile in ./frontend
    ports:
      - "5173:5173"  # Adjust for your frontend framework (Vite, React, etc.)
    depends_on:
      - backend
    networks:
      - frontend_net
  
  backend:
    build: ./backend  # Assumes you have a Dockerfile in ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy  # ✅ Ensures the backend waits for PostgreSQL
    networks:
      - frontend_net
      - backend_net

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    # ports:
    #   - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:  # ✅ Ensures PostgreSQL is ready before backend starts
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      retries: 5
    networks:
      - backend_net

volumes:
  pgdata:

networks:
  frontend_net:  # Hier wird ein eigenes Netzwerk definiert
    driver: bridge
  backend_net:  # Hier wird ein eigenes Netzwerk definiert
    driver: bridge